export interface GameSaveEntry {
  id: string;
  label: string;
  lsTerms: string[];
  idbTerms: string[];
  storage: ("localStorage" | "indexedDB" | "memory" | "external")[];
  notes?: string;
}

export const GAME_SAVE_MAP: GameSaveEntry[] = [
  {
    id: "eaglercraft",
    label: "Eaglercraft",
    lsTerms: ["eaglercraft", "EaglercraftX", "eagler", "EaglerBungee"],
    idbTerms: ["eaglercraft", "EaglercraftX", "eagler"],
    storage: ["localStorage", "indexedDB"],
    notes: "Minecraft clone — worlds stored in IndexedDB, settings in localStorage",
  },
  {
    id: "retro-bowl",
    label: "Retro Bowl",
    lsTerms: ["retrobowl", "RetroB", "rb_", "rbsave", "retroBowl"],
    idbTerms: ["retrobowl", "retroBowl"],
    storage: ["localStorage"],
    notes: "HTML5 football game — save data in localStorage",
  },
  {
    id: "drift-hunters",
    label: "Drift Hunters",
    lsTerms: ["drifthunters", "DriftHunters", "drift_hunters", "dh_"],
    idbTerms: ["drifthunters"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "tomb-of-the-mask",
    label: "Tomb of the Mask",
    lsTerms: ["tombofthemask", "TombOfTheMask", "tomb_mask", "totm"],
    idbTerms: ["tombofthemask", "totm"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "super-hot",
    label: "Super Hot",
    lsTerms: ["superhot", "SuperHot", "super_hot"],
    idbTerms: ["superhot"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "brawl-stars",
    label: "Brawl Stars",
    lsTerms: ["brawlstars", "BrawlStars", "brawl_stars", "brawl"],
    idbTerms: ["brawlstars"],
    storage: ["localStorage"],
    notes: "Fan-made HTML5 clone — saves in localStorage",
  },
  {
    id: "block-blast",
    label: "Block Blast",
    lsTerms: ["blockblast", "BlockBlast", "block_blast", "blockBlast"],
    idbTerms: ["blockblast"],
    storage: ["localStorage"],
    notes: "HTML5 puzzle game — saves in localStorage",
  },
  {
    id: "bitlife",
    label: "BitLife",
    lsTerms: ["bitlife", "BitLife", "bit_life"],
    idbTerms: ["bitlife", "BitLife"],
    storage: ["localStorage"],
    notes: "Unity WebGL — saves in localStorage",
  },
  {
    id: "escape-road",
    label: "Escape Road",
    lsTerms: ["escaperoad", "EscapeRoad", "escape_road"],
    idbTerms: ["escaperoad"],
    storage: ["localStorage", "external"],
    notes: "Uses Firebase for leaderboards; local progress in localStorage",
  },
  {
    id: "car-king",
    label: "Car King",
    lsTerms: ["carking", "CarKing", "car_king"],
    idbTerms: ["carking"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "drift-boss",
    label: "Drift Boss",
    lsTerms: ["driftboss", "DriftBoss", "drift_boss"],
    idbTerms: ["driftboss"],
    storage: ["localStorage"],
    notes: "Flash/HTML5 game via Ruffle — minimal persistent data",
  },
  {
    id: "drive-mad",
    label: "Drive Mad",
    lsTerms: ["drivemad", "DriveMad", "drive_mad", "dmad"],
    idbTerms: ["drivemad"],
    storage: ["localStorage"],
    notes: "HTML5 game from Poki CDN — saves in localStorage",
  },
  {
    id: "rocket-soccer",
    label: "Rocket Soccer Derby",
    lsTerms: ["rocketsoccer", "RocketSoccer", "rocket_soccer"],
    idbTerms: ["rocketsoccer"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "snowball-io",
    label: "Snowball.io",
    lsTerms: ["snowballio", "SnowballIO", "snowball"],
    idbTerms: ["snowballio", "snowball"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "chess",
    label: "Chess Classic",
    lsTerms: ["chess", "Chess"],
    idbTerms: ["chess"],
    storage: ["localStorage"],
    notes: "HTML5 chess from YouTube Playables CDN — localStorage",
  },
  {
    id: "slope",
    label: "Slope",
    lsTerms: ["slope", "Slope"],
    idbTerms: ["slope"],
    storage: ["localStorage"],
    notes: "WebGL game — high scores in localStorage",
  },
  {
    id: "10-minutes-till-dawn",
    label: "10 Minutes Till Dawn",
    lsTerms: ["10minutes", "tenminutes", "TenMinutes", "mindawn", "10min"],
    idbTerms: ["10minutes", "mindawn"],
    storage: ["localStorage"],
    notes: "Unity WebGL — PlayerPrefs in localStorage",
  },
  {
    id: "baby-sniper",
    label: "Baby Sniper Vietnam",
    lsTerms: ["babysniper", "BabySniper", "baby_sniper"],
    idbTerms: ["babysniper"],
    storage: ["localStorage"],
    notes: "HTML5 game — saves in localStorage",
  },
  {
    id: "five-nights-at-winstons",
    label: "Five Nights at Winston's",
    lsTerms: ["fnaw", "winstons", "FiveNights", "fiveNights"],
    idbTerms: ["fnaw"],
    storage: ["localStorage"],
    notes: "Custom JS fan game — progress in localStorage",
  },
  {
    id: "1v1-lol",
    label: "1v1.lol",
    lsTerms: ["1v1", "1v1lol", "OneLoveLol"],
    idbTerms: ["1v1"],
    storage: ["localStorage"],
    notes: "HTML5 battle game — localStorage",
  },
  {
    id: "bikers-republic",
    label: "Bikers Republic",
    lsTerms: ["bikers", "bikersrepublic", "BikerRepublic"],
    idbTerms: ["bikers"],
    storage: ["localStorage"],
    notes: "HTML5 game — localStorage",
  },
  {
    id: "counter-strike",
    label: "Counter Strike",
    lsTerms: ["counterstrike", "CounterStrike", "counter_strike", "cs_"],
    idbTerms: ["counterstrike"],
    storage: ["localStorage"],
    notes: "HTML5 CS clone — localStorage",
  },
  {
    id: "geometry-dash",
    label: "Geometry Dash",
    lsTerms: ["geometrydash", "GeometryDash", "geometry_dash", "gdash"],
    idbTerms: ["geometrydash"],
    storage: ["localStorage"],
    notes: "HTML5 clone — level progress in localStorage",
  },
  {
    id: "moto-x3m",
    label: "Moto X3M",
    lsTerms: ["motox3m", "MotoX3M", "moto_x3m", "moto"],
    idbTerms: ["motox3m"],
    storage: ["localStorage"],
    notes: "HTML5 bike game — level/star progress in localStorage",
  },
  {
    id: "stickman-merge",
    label: "Stickman Merge",
    lsTerms: ["stickmanmerge", "StickmanMerge", "stickman_merge", "stickman"],
    idbTerms: ["stickmanmerge"],
    storage: ["localStorage"],
    notes: "HTML5 idle game — unit levels in localStorage",
  },
  {
    id: "quake3",
    label: "Quake 3",
    lsTerms: ["quake", "Quake", "q3", "quake3"],
    idbTerms: ["quake"],
    storage: ["localStorage", "memory"],
    notes: "WebAssembly game — minimal localStorage, mostly in-memory",
  },
];
